run:
	clear
	gcc -Wall -Wno-unused-variable -o main *.c
	./main

clean:
	rm -f main

# run:
# 	clear
# 	make main
# 	./main in
#
# example:
# 	clear
# 	make main
# 	./main ex
#
# main: main.c
# 	gcc -Wall -Wno-unused-variable main.c -o main
